version: '2'
services:
  mongo3-2-10_rs0-0:
    hostname: mongo0
    container_name: mongo3-2-10_rs0-0
    image: mongo:3.2.10

    command: mongod --port 27017 --dbpath /data/db --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    expose:
      - "27017"
    networks:
      db:
        ipv4_address: 172.19.0.2
    environment:
      TERM: xterm
    volumes:
      - ./start.sh:/rs-init.sh
      - /etc/localtime:/etc/localtime:ro
      - /mongo_3.2.10_rs/data0:/data/db
  mongo3-2-10_rs0-1:
    hostname: mongo1
    container_name: mongo3-2-10_rs0-1
    image: mongo:3.2.10

    command: mongod --port 27017 --dbpath /data/db --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    ports:
      - 27018:27017
    expose:
      - "27017"
    networks:
      db:
        ipv4_address: 172.19.0.3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_3.2.10_rs/data1:/data/db
  mongo3-2-10_rs0-2:
    hostname: mongo2
    container_name: mongo3-2-10_rs0-2
    image: mongo:3.2.10

    command: mongod --port 27017 --dbpath /data/db --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    ports:
      - 27019:27017
    expose:
      - "27017"
    networks:
      db:
        ipv4_address: 172.19.0.4
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mongo_3.2.10_rs/data2:/data/db

networks:
  db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24