config: {}
networks:
  - name: lxdbr0
    type: bridge
    config:
      ipv4.address: 10.245.147.1/24
      ipv4.nat: "true"
      ipv6.address: none
      raw.dnsmasq: |
        dhcp-range=10.245.147.50,10.245.147.200,255.255.255.0,12h

storage_pools:
  - name: default
    driver: dir

profiles:
  - name: default
    devices:
      root:
        type: disk
        pool: default
        path: /
      eth0:
        type: nic
        network: lxdbr0
        name: eth0

cluster: null
